name: Release

on:
  pull_request:
    types: [closed]

jobs:
  call:
    uses: bedita/github-workflows/.github/workflows/release.yml@main
    with:
      main-branch: 'master'
      dist-branches: '["master", "1.x"]'
