name: Release

on:
  pull_request:
    types: [closed]
  pull_request_target:

jobs:
  release-job:
    uses: bedita/github-workflows/.github/workflows/release.yml@feat/github-script
    with:
      main_branch: 'master'
      dist_branches: '["master", "1.x"]'
      # version_ini_path: config/version.ini
      # version_ini_prefix: "[WebTools]\nversion="

# test 1 - version ini from fork
